import * as fs from 'fs';
import * as path from 'path';

import {defineConfig} from "cypress";
import registerCodeCoverageTasks from "@cypress/code-coverage/task";


export default defineConfig({
  env: {
    "coverage": true,
    "language": "en",
    "codeCoverage": {
      "enabled": true
    },
    "pgp": false,
    "init_password": "Password12345#",
    "user_password": "ACollectionOfDiplomaticHistorySince_1966_ToThe_Pr esentDay#",
    "field_types": [
      "Single-line text input",
      "Multi-line text input",
      "Selection box",
      "Multiple choice input",
      "Checkbox",
      "Attachment",
      "Terms of service",
      "Date",
      "Date range",
      "Voice",
      "Group of questions"
    ],
    "takeScreenshots": true,
    // The manual uses no narrow capture and the accessibility scan is a check of
    // its own: both are available, neither is paid for on every screenshot.
    "mobileScreenshots": false,
    "a11yOnScreenshots": false
  },
  e2e: {
    setupNodeEvents(on, config) {
      // In-memory store shared across spec files within a single run. Cypress.env()
      // values set at runtime do not persist between specs, so the passwords
      // generated by the admin in 07 are kept here and exposed to later specs as
      // the Cypress.env("users_passwords") dict indexed by username.
      const users_passwords: Record<string, string> = {};

      // All your plugin logic goes here
      registerCodeCoverageTasks(on, config);

      on("before:browser:launch", (browser, launchOptions) => {
        if (browser.family === "chromium") {
          // The window is far taller than any page the manual photographs.
          // Cypress cannot grow the viewport beyond the window: a taller page
          // kept its scrollbar and was rendered shrunk to fit and then blown
          // back up to the requested size, which is what made the images of the
          // long pages look coarse. With room to spare the page is rendered at
          // its own size and captured one to one.
          launchOptions.args.push("--window-size=1920,4000");
          launchOptions.args.push("--force-device-scale-factor=1");
          // No scrollbars in the captures: they are furniture of the window,
          // not of the interface the manual describes, and they were showing up
          // along the right and the bottom edge of most images.
          launchOptions.args.push("--hide-scrollbars");
        }
        return launchOptions;
      });

      on("after:screenshot", (details) => {
        if (details.path.includes("failed")) return;

        const language = config.env.language;

        // The name of a screenshot carries its own folders: "admin/foo" for the
        // desktop capture and "mobile/admin/foo" for the mobile one. Keeping
        // only the last two segments of the path collapsed the two onto the same
        // destination, so the mobile capture overwrote the desktop one and the
        // documentation ended up illustrated at 375px. The destination is
        // therefore everything below the folder of the spec.
        const specRoot = path.join(config.screenshotsFolder, details.specName);
        const relative = path.relative(specRoot, details.path).replace(/\.png$/, "");
        const name = relative.startsWith("..")
          ? details.path.replace(".png", "").split("/").slice(-2).join("/")
          : relative;

        const destPath = path.resolve(
          __dirname,
          "../documentation/images",
          name + "." + language + ".png"
        );
        const destDir = path.dirname(destPath);
        if (!fs.existsSync(destDir)) fs.mkdirSync(destDir, { recursive: true });
        fs.copyFileSync(details.path, destPath);
        return { path: destPath };
      });

      on("task", {
        log(message) {
          console.log(message);
          return null;
        },
        table(message) {
          console.table(message);
          return null;
        },
        storeUserPassword({username, password}) {
          users_passwords[username] = password;
          return null;
        },
        getUsersPasswords() {
          return users_passwords;
        },
      });

      return config;
    },
    baseUrl: "https://127.0.0.1:8443",
    viewportWidth: 1280,
    viewportHeight: 720
  },
  defaultCommandTimeout: 20000,
});
