language: python
services:
  - mysql
python:
  - "2.7"
before_install:
  - ./scripts/travis/before_install.sh
install:
  - ./scripts/travis/install.sh
before_script:
  - ./scripts/travis/before_script.sh
script:
  - ./scripts/travis/script.sh
