// Load the passwords generated by the administrator in 07 into a Cypress
// environment variable, indexed by username. The values are carried across
// specs through an in-memory task store (Cypress.env set at runtime does not
// persist between specs).
before(() => {
  cy.task("getUsersPasswords").then(users_passwords => {
    Cypress.env("users_passwords", users_passwords);
  });
});

describe("Recipient first login", () => {
  // the credentials generated by the administrator are delivered to the
  // user, which is required to replace the password with its own upon the first
  // access; the password set here is the encryption password of the account.
  it("should require password change upon successful authentication", () => {
    cy.login_receiver("Recipient", Cypress.env("users_passwords")["Recipient"], "#/login", true);
    cy.get('input[name="changePasswordArgs.password"]').should('be.visible');
    cy.takeScreenshot("user/password_change_on_first_login");
    cy.get('input[name="changePasswordArgs.password"]').should('be.visible').clear().type(Cypress.env("user_password"));
    cy.get('input[name="changePasswordArgs.confirm"]').should('be.visible').clear().type(Cypress.env("user_password"));
    cy.get('button[name="submit"]').click();
    cy.waitForUrl("/recipient/home");
    cy.visit("/#/recipient/preferences");
    cy.takeScreenshot("user/preferences");
    cy.get('#tab2').click();
    cy.takeScreenshot("user/password_change");
    cy.get("#SupportLink").click();
    // an authenticated user is not asked for its address: it is the one of the account
    cy.get(".modal-dialog").should("be.visible").then($modal => {
      if ($modal.find('[data-cy="support-tab-new"]').length) {
        cy.get('[data-cy="support-tab-new"]').click();
      }
    });
    cy.get("#support-request-message").should("be.visible");
    cy.takeScreenshot("user/modal_support", ".modal-dialog");
    cy.get(".modal #modal-action-cancel").click();
    cy.logout();
  });

  // a user that has completed the registration and set its own
  // encryption password performs a subsequent login with the correct password.
  it("should be able to login with the new password", () => {
    cy.login_receiver();
    cy.logout();
  });

  // the same user is denied a subsequent login when the password is
  // wrong; the session is not opened and the login page keeps being displayed.
  it("should not be able to login with a wrong password", () => {
    cy.visit("#/login");
    cy.takeScreenshot("forward/login");
    cy.get("[name=\"username\"]").type("Recipient");
    cy.get("[name=\"password\"]").type("ThisIsNotTheRightPassword#1");
    cy.get("#login-button").click();

    // the refusal is told to the user: waiting for the message is also what
    // makes the capture show it, instead of the form as it was before answering
    cy.get("#LoginError").should("be.visible");
    cy.url().should("include", "#/login");
    cy.get("#LogoutLink").should("not.exist");
    cy.takeScreenshot("forward/login_error_detail", "#login-form");
  });

  it("should be able to retrieve the account recovery key", () => {
    cy.login_receiver("Recipient", Cypress.env("user_password"), "#/login", true);
    cy.waitForUrl("/recipient");
    cy.visit("/#/recipient/preferences");
    cy.takeScreenshot("user/preferences");
    cy.get( "#account_recovery_key").click();
    cy.get("[name='secret']").type(Cypress.env("user_password"));
    cy.get("#confirm").click();

    // The recovery key is shown but hidden by default.
    cy.get('#AccountRecoveryKey').should('be.visible').and('have.attr', 'type', 'password');
    cy.takeScreenshot("user/recoverykey", ".modal-dialog");
    cy.takeScreenshot("user/account_recovery_key", ".modal-dialog");

    // The show/hide toggle reveals and re-hides the recovery key.
    cy.get('#toggle-visibility').click();
    cy.get('#AccountRecoveryKey').should('have.attr', 'type', 'text');
    cy.takeScreenshot("user/recoverykey_revealed", ".modal-dialog");
    cy.get('#toggle-visibility').click();
    cy.get('#AccountRecoveryKey').should('have.attr', 'type', 'password');

    cy.get("#close").click();
    cy.logout()
  });

  it("should be able to enable two factor authentication", () => {
    cy.login_receiver("Recipient", Cypress.env("user_password"), "#/login", true);
    cy.waitForUrl("/recipient");
    cy.visit("/#/recipient/preferences");
    cy.get("[name='two_factor']").click();
    cy.wait(1000);
    cy.takeScreenshot("user/2fa", ".modal-dialog");
    cy.get("#close").click();
    cy.logout();
  });
});

describe("Recipient2 first login", () => {
  it("should require password change upon successful authentication", () => {
    const password = Cypress.env("init_password") + "abc";
    cy.login_receiver("Recipient2", Cypress.env("users_passwords")["Recipient2"], "#/login", true);
    cy.get('input[name="changePasswordArgs.password"]').should('be.visible').clear().type(password);
    cy.get('input[name="changePasswordArgs.confirm"]').should('be.visible').clear().type(password);
    cy.get('button[name="submit"]').click();
    cy.logout();
  });
});

describe("Recipient2 voluntary password change", () => {
  it("should perform voluntary password change", () => {
    const password = Cypress.env("init_password") + "abc";
    cy.login_receiver("Recipient2", password, "#/login", false);
    cy.get("#PreferencesLink").click();
    cy.get(".password").click();
    cy.get('input[name="changePasswordArgs.current"]').should('be.visible').clear().type(password).should('have.value', password);
    cy.get('input[name="changePasswordArgs.password"]').should('be.visible').clear().type(Cypress.env("user_password")).should('have.value', Cypress.env("user_password"));
    cy.get('input[name="changePasswordArgs.confirm"]').should('be.visible').clear().type(Cypress.env("user_password")).should('have.value', Cypress.env("user_password"));
    cy.get('button[name="submit"]').should('be.enabled').click();
    cy.logout();
  });
});

// The four accounts go through the same first access: the form, the replacement of the password, the
// landing
describe("first login of the accounts the administrator created", () => {
  const accounts = [
    {username: "Custodian", home: "/custodian/home"},
    {username: "Admin2", home: "/admin/home"},
    {username: "Auditor", home: "/auditor/home"},
    {username: "Analyst", home: "/analyst/home"}
  ];

  accounts.forEach(({username, home}) => {
    it(`should require ${username} to replace the password and land on ${home}`, () => {
      cy.login_user(username, Cypress.env("users_passwords")[username], "#/login", true);
      cy.get('input[name="changePasswordArgs.password"]').should('be.visible').clear().type(Cypress.env("user_password"));
      cy.get('input[name="changePasswordArgs.confirm"]').should('be.visible').clear().type(Cypress.env("user_password"));
      cy.get('button[name="submit"]').click();
      cy.url().should("include", home);
      cy.logout();
    });
  });
});
